language: ruby
cache: bundler
rvm:
- 2.2.1
addons:
  postgresql: '9.3'
before_install:
- sudo add-apt-repository --yes ppa:baineri/opt-qt551-trusty
- sudo apt-get update -qq
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
  - sudo apt-get -y install qt55[QTPACKAGE]

before_script:
- psql -c 'create database bc_test;' -U postgres
script:
- source /opt/qt55/bin/qt55-env.sh
- /opt/qt55/bin/qmake
- make
- bundle exec rake db:migrate RAILS_ENV=test VERBOSE=false
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec -fp -t ~skip spec/
notifications:
  slack:
env:
  - APP_URL=http://www.biblechallenges.com
