language: ruby
cache: bundler
rvm:
- 2.2.1

addons:
  postgresql: "9.3"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - psql -c 'create database bc_test;' -U postgres
    # - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rspec spec/
