language: ruby
cache: bundler
rvm:
- 2.2.1
addons:
  postgresql: '9.3'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database bc_test;' -U postgres
script:
- 
- bundle exec rake db:migrate RAILS_ENV=test VERBOSE=false
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec -fp -t ~skip spec/
notifications:
  slack:
    secure: Nsa5gZkIqSGQDTFO9eFmFQm1yKa1rd62UOpNMiHdDYG3Ux2JIJrwj21yY4wQnwjPr1xzkAcH1zSzb83zysBSpaApBiUvv2K5Kuo2+5yrzQg7o/1Quh01Zvhf/tCphrD0xZXZnKoSKHsZhtXguf2Bvq6dr9ONjSYe+WEBZJI5Itk=
    secure: GqoMfyPpGws3kPi87pTbmdlRWy/qttgXebo03iFEnXfZUXdCUCDlf5fPMP2uU8nMVQ59sCp+Zc+Ar4v7W9JW26Y3Xf3NFAzco1vvFAUPHAXh5Rrw0WiRhkdiVb8zcdCc+cjX7NTsUNO1F/4yqtdGbfrQI3JLFVKkWev57TYrM6Y=
