# Site settings
title: BibleChallenges
email: pdbradley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Biblechallenges.com is a Bible reading scheduler that emails 
  your reading to you daily.  You can read alone or in groups.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://biblechallenges.com"

# Build settings
markdown: kramdown
