# Site settings
title: Bible Challenges Blog
#email: pdbradley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bible Challenges lets you create and join scheduled Bible
  reading programs with your friends.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://biblechallenges.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
