production:
  pool: <%= ENV['DATABASE_POOL_SIZE'] || 10 %>
  url: <%= ENV['DATABASE_URL'] %>

defaults: &defaults
  adapter: postgresql
  # template: template0
  encoding: utf8
  pool: 5
  timeout: 5000
  # host: localhost

development:
  <<: *defaults
  database: bc_development_may07

test:
  <<: *defaults
  database: bc_test
