production:
  pool: <%= ENV['DATABASE_POOL_SIZE'] || 10 %>
  url: <%= ENV['DATABASE_URL'] %>

defaults: &defaults
  adapter: postgresql
  # encoding: unicode
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  host: localhost

development:
  <<: *defaults
  database: bc_development

test:
  <<: *defaults
  database: bc_test
