production:
  pool: <%= ENV['DATABASE_POOL_SIZE'] || 10 %>
  url: <%= ENV['DATABASE_URL'] %>

defaults: &defaults
  adapter: postgresql
  template: template0
  host: localhost

development:
  <<: *defaults
  database: bc_development

test:
  <<: *defaults
  database: bc_test
