defaults: &defaults
  adapter: postgresql
  template: template0
  host: localhost

production:
  <<: *defaults
  database: bc_production

development:
  <<: *defaults
  database: bc_development

test:
  <<: *defaults
  database: bc_test
